apiVersion: v2
name: pinpoint-collector
description: A Helm chart for Pinpoint Collector
type: application
# chart version. 
version: 0.1.0
# version number of the application being deployed. 
appVersion: 2.1.0
keywords:
    - collector