---


######## nginx ingress controller #########
- name: ingress-nginx  controller 설치 - ssl_passthrough 사용 (enable ssl_passthrough)
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: "{{INGRESS_NGINX_CHART}}"
    chart_version: "{{INGRESS_NGINX_CHART_VERSION}}"
    release_namespace: "{{INGRESS_NGINX_NAMESPACE}}"
    create_namespace: true   
    wait: true
    values:
      controller: 
        extraArgs:
          enable-ssl-passthrough: true
  when: INGRESS_NGINX_ENABLE_SSLPASSTHROUGH == 'Y'
  register: output
  tags: 
    - ingress-nginx
    - k8s-basic
 

- name: nginx ingress controller 설치- ssl_passthrough 미사용 (disable ssl_passthrough)
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: "{{INGRESS_NGINX_CHART}}"
    chart_version: "{{INGRESS_NGINX_CHART_VERSION}}"
    release_namespace: "{{INGRESS_NGINX_NAMESPACE}}"
    create_namespace: true   
    wait: true
  when: INGRESS_NGINX_ENABLE_SSLPASSTHROUGH == 'N'
     
  register: output
  tags: 
    - ingress-nginx
    - k8s-basic
  

- debug:
    var: output
  tags: 
    - ingress-nginx
    - k8s-basic
   
