---
- name: "[pre] apt update"
  apt:
    update_cache: yes
  become: true
  tags: 
    - pre
- name: "[pre] zip 설치"
  apt: 
    name: zip    
  become: true  
  tags: 
  - pre
  

- name: "[pre] unzip 설치"
  apt: 
    name: unzip
  become: true
  tags: 
  - pre
