---
- name: "[pre] apt update"
  apt:
    update_cache: yes
  become: true
  tags: 
    - pre
- name: "[pre] zip 설치"
  apt: 
    name: zip    
  become: true  
  tags: 
  - pre
  

- name: "[pre] unzip 설치"
  apt: 
    name: unzip
  become: true
  tags: 
  - pre

- name: "[pre] down 디렉토리 생성"
  file:
    path: "{{ INSTALL_DOWN_ROOT }}/down"
    state: directory
  tags: 
    - install-down
    - pre

- name: "pip 설치"
  apt: 
    name: python3-pip   
  become: true  
  tags: 
  - pip
  - ansible-module
  
- name: install ansible server module pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 
      - docker
      - docker-compose
  tags: 
    - ansible-module

- name: helm3 설치
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    chdir: "{{ INSTALL_DOWN_ROOT }}/down/"
  tags: 
    - helm3 
    - pre    

- name: bitnami  repository 추가 
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
  tags: 
    - bitnami-repo
    - helm-repo
    
- name: ingress-nginx  repository 추가 
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  tags: 
    - nginxctr-repo
    - helm-repo 
    
- name: jenkins  repository 추가 
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io
  tags: 
    - jenkins-repo
    - helm-repo

############### helm repo update ####################
- name: helm repo update
  shell: |
    helm repo update
  tags: 
    - helm-update
    - helm-repo




   