apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pinpoint-web.fullname" . }}
  labels:
{{ include "pinpoint-web.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "pinpoint-web.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pinpoint-web.labels" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
       - name: wait-mysql
         image: alpine
         command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 pinpoint-mysql 3306 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: ui
              containerPort: {{ .Values.serverPort }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ template "pinpoint-web.fullname" . }}
          - secretRef:
              name: {{ template "pinpoint-web.fullname" . }}
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: {{ .Values.serverPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: {{ .Values.serverPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
