---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always
  when: ansible_distribution == 'Ubuntu'



- name: install on ubuntu 
  import_tasks: install.yml  
  
