---
######## k3d #########

- name: " k3d 디렉토리 생성"
  file:
    path: "{{ component.INSTALL_ROOT }}/k3d"
    state: directory
  tags: 
    - k3d-dir
    - k3d 
    
   

- name: k3d config-file  업로드 서버로
  template:
    src: k3d/k3d-config.yml.j2
    dest: "{{ component.INSTALL_ROOT }}/k3d/k3d-config.yml"
  tags: 
    - k3d-config-up
    - k3d 
    



- name: k3d 설치 
  shell: |
    k3d cluster create --config  {{ component.INSTALL_ROOT }}/k3d/k3d-config.yml --wait
    k3d kubeconfig write {{K3D_ClUSTER_NAME}} 
  register: output
  tags: 
    - k3d 
       
    
- debug:
    var: output
  tags: 
    - k3d
    

- name: waiting for pod status Ready
  shell: |
      kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n kube-system
  tags: 
    - k3d
    



- name: "k3d fetch remote kubeconfig"
  ansible.builtin.fetch:
    src: "/home/{{ansible_user}}/.k3d/kubeconfig-{{K3D_ClUSTER_NAME}}.yaml"
    dest: "{{LOCAL_USER_HOME}}/.kube/k8s/kubeconfig"
    flat: yes
  tags: 
    - k3d-config-fetch
    - k3d
    
  when: ansible_distribution == 'Ubuntu'

- name: "kubeconfig remote.ip replace"
  local_action: shell
    {{ command.SED_REPLACE_COMMAND }}
  tags: 
    - k3d-config-sed
    - k3d
    
  when: ansible_distribution == 'Ubuntu'