- name: My Second Ansible
  hosts: all
  tasks:

  - name: "[pre] apt update"
    apt:
      update_cache: yes
    become: true
    tags:
      - pre

  - name: "docker 설치"
    shell: |
      curl -fsSL https://get.docker.com/ | sudo sh
      sudo usermod -a -G docker {{ansible_user}}   # ansible_user는 hosts-vm에 설정된 user
    tags:
      - docker
      - k8s-basic

  - name: Start docker
    service:
      name: docker
      state: restarted
    become: true
    tags:
      - docker
      - k8s-basic
  # tag를 이용하면 원하는 구성요소만 설치할 수 있음
  - name: reset ssh connection to allow user changes to affect ‘current login user’
    meta: reset_connection # builtin 모듈
    tags:
      - docker
      - k8s-basic      

  - name: k9s 설치
    shell: |
      curl -sL https://github.com/derailed/k9s/releases/download/v0.25.21/k9s_Linux_x86_64.tar.gz | sudo tar xfz - -C /usr/local/bin k9s
    tags:
      - k9s
      - k8s-basic      